<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="MAIN" Id="{669ec0ec-14f4-4f97-93d0-387805f25cf8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	TP0: FB_Torque_prediction;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TP0();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>